<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets\vcms_icon.ico</ApplicationIcon> 
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="assets\" />
    <Folder Include="docs\" />
    <Folder Include="tests\" />
  </ItemGroup>

</Project>